# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "jacky-demo-tf-state"
    dynamodb_table = "jacky-demo-tf-state-locking"
    encrypt        = true
    key            = "jacky/quick-start/./terraform.tfstate"
    region         = "eu-central-1"
  }
}
